server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /env.js {
        add_header Content-Type application/javascript;
        return 200 "window._env_ = {
            VITE_API_URL: \"$VITE_API_URL\"
        };";
    }
}
